name: psychoai
description: "Pré-análise psicanalítica com IA"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI/UX
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  animations: ^2.0.11
  flutter_animate: ^4.5.0

  # Estado
  provider: ^6.1.1

  # API
  dio: ^5.4.0
  http: ^1.2.0

  # Segurança
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3

  # Formulários
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.0.0

  # Gráficos e Visualização
  fl_chart: ^0.71.0

  # Roteamento
  go_router: ^15.1.2

  # JSON
  json_annotation: ^4.8.1

  # Data/Tempo
  intl: ^0.20.2

  # Storage Local
  hive_flutter: ^1.1.0

  # Database
  mongo_dart: ^0.10.3

  # Icons
  phosphor_flutter: ^2.0.1

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  glassmorphism: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  very_good_analysis: ^5.1.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

    # assets:
  # - assets/images/
  # - assets/icons/
